version: "3.9"

services:
  upload:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops-upload
    ports:
      - "8001:8000"
    environment:
      API_BEARER_TOKEN: YOUR_TOKEN
    volumes:
      - my-uploads:/uploads
    networks:
      - app-net

  stats:
    build:
      context: .
      dockerfile: Dockerfile.stats
    container_name: devops-stats
    ports:
      - "8002:8000"
    environment:
      API_BEARER_TOKEN: YOUR_TOKEN
    volumes:
      - my-uploads:/uploads
    networks:
      - app-net

  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - upload
      - stats
    networks:
      - app-net

volumes:
  my-uploads:

networks:
  app-net:
    driver: bridge
