apiVersion: v1
kind: Namespace
metadata:
  name: gestionale
---
apiVersion: v1
kind: Secret
metadata:
  name: upload-secret
  namespace: gestionale
type: Opaque
stringData:
  API_BEARER_TOKEN: "token1234"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-uploads-pvc
  namespace: gestionale
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
