apiVersion: v1
kind: Service
metadata:
  name: upload
  namespace: gestionale
  labels:
    app: upload
  annotations:
    prometheus.io/port: "metrics"
    prometheus.io/scrape: "true"
spec:
  #type: LoadBalancer
  type: ClusterIP
  selector:
    app: upload
  ports:
    - name: http
      port: 8000
      targetPort: 8000
 