apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: upload-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: upload
  namespaceSelector:
    matchNames:
      - gestionale
  endpoints:
    - port: http
      interval: 10s
      path: /metrics




